### ISSUE TITLE
multi-line command hangs GDB

### ISSUE THREAD

**Issue by YalandHong** [lebr0nli/GEP#19]
When you input a multi-line GDB command (e.g. `while`), GEP hangs and CPU usage increases to 100%.

![image](https://github.com/lebr0nli/GEP/assets/52960068/75b8221f-e9ed-4151-a6c6-8853592377e4)

In normal GDB, the result should be:
![image](https://github.com/lebr0nli/GEP/assets/52960068/1d435f93-70a4-47b7-a1d7-2a0c6842f8d1)

It may not be a serious problem since I don't use multi-line commands very often. But it indeed hangs and crashes GDB.

**Comment by lebr0nli** [comment]
Hello, and thank you for reporting the bug!

I've implemented some initial support for multi-line commands in pull request #20. That patch should address this issue, but it's important to note that it may not be perfect.
Some cases might be challenging to support due to limitations in GDB's API. For instance, we currently can't display correct indentation for nested if/while statements.

Could you kindly verify if the patch is working for you?

Additionally, I'd like to mention that I've recently updated GEP to utilize a virtual environment (venv) to accommodate the latest version of pwndbg. If you haven't done so already, you might need to use the latest installation script to reinstall GEP before applying this patch.
